# Generated by Django 3.2 on 2023-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='senderId',
        ),
        migrations.AddField(
            model_name='message',
            name='senderName',
            field=models.CharField(default='user', max_length=128),
        ),
    ]
