# Generated by Django 3.2 on 2023-08-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0005_delete_message'),
        ('message', '0002_auto_20230825_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adminId', models.IntegerField()),
                ('inviteId', models.IntegerField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manage.group')),
            ],
            options={
                'db_table': 'team_message',
            },
        ),
    ]
