# Generated by Django 3.2 on 2023-08-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
        ('group_manage', '0005_delete_message'),
        ('message', '0003_teammessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatId', models.AutoField(primary_key=True, serialize=False)),
                ('leaderId', models.IntegerField(default=0)),
                ('chatType', models.IntegerField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manage.group')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.chat')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.userinfo')),
            ],
            options={
                'db_table': 'chat_user',
            },
        ),
    ]
