# Generated by Django 3.2 on 2023-08-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_chat_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.chat'),
            preserve_default=False,
        ),
    ]
