# Generated by Django 3.2 on 2023-08-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20230831_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatName',
            field=models.CharField(default='hhh', max_length=128),
        ),
    ]
