# Generated by Django 3.2 on 2023-08-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20230831_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adminId', models.IntegerField()),
                ('inviteId', models.IntegerField()),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.chat')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
