# Generated by Django 3.2 on 2023-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20230831_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chatName',
            field=models.CharField(default='chat', max_length=128),
        ),
    ]
