# Generated by Django 3.2 on 2023-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20230901_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
