# Generated by Django 3.2 on 2023-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20230901_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chatId',
            field=models.IntegerField(default=0),
        ),
    ]
