# Generated by Django 3.2 on 2023-08-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manage.group')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.IntegerField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manage.group')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.userinfo')),
            ],
            options={
                'db_table': 'groupUsers',
            },
        ),
    ]
