# Generated by Django 3.2 on 2023-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupName',
            field=models.CharField(default='aa', max_length=128),
        ),
    ]
