# Generated by Django 3.2 on 2023-08-25 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0003_alter_group_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='buildTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='groupBuilder',
            field=models.CharField(default='new_group', max_length=128),
        ),
    ]
