# Generated by Django 3.2 on 2023-08-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0004_auto_20230825_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
