# Generated by Django 3.2 on 2023-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prototypes',
            fields=[
                ('protoId', models.AutoField(primary_key=True, serialize=False)),
                ('protoInclude', models.TextField(default='')),
                ('protoName', models.CharField(max_length=32)),
                ('workIs', models.IntegerField(default='0')),
            ],
        ),
    ]
