# Generated by Django 3.2 on 2023-08-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prototypes',
            table='prototypes',
        ),
    ]
