# Generated by Django 3.2 on 2023-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_manage', '0002_alter_prototypes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypes',
            name='is_vaild',
            field=models.BooleanField(default='1'),
        ),
    ]
