# Generated by Django 3.2 on 2023-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_manage', '0004_alter_prototypes_protoinclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypes',
            name='protoInclude',
            field=models.TextField(default=''),
        ),
    ]
