# Generated by Django 3.2 on 2023-08-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
        ('station_manage', '0002_delete_file_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_manage.files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.userinfo')),
            ],
            options={
                'db_table': 'file_users',
            },
        ),
    ]
