# Generated by Django 3.2 on 2023-08-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0003_file_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_users',
            old_name='file_id',
            new_name='fileId',
        ),
        migrations.RenameField(
            model_name='file_users',
            old_name='user_id',
            new_name='userId',
        ),
    ]
