# Generated by Django 3.2 on 2023-08-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0005_alter_works_create_time'),
        ('file_manage', '0004_auto_20230825_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Vers',
            fields=[
                ('fileId', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=32)),
                ('fileInclude', models.TextField(default='')),
                ('fileUrl', models.CharField(max_length=255)),
                ('fileVersion', models.IntegerField(default=1)),
                ('fileIs', models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='station_manage.works')),
            ],
        ),
    ]
