# Generated by Django 3.2 on 2023-08-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0005_file_vers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file_vers',
            table='file_vers',
        ),
    ]
