# Generated by Django 3.2 on 2023-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0006_alter_file_vers_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_vers',
            name='fileId',
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name='file_vers',
            name='fileName',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
