# Generated by Django 3.2 on 2023-08-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0008_alter_works_create_time'),
        ('user_info', '0001_initial'),
        ('file_manage', '0007_auto_20230826_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Message',
            fields=[
                ('id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('messageIs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_manage.files')),
                ('receiveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveId', to='user_info.userinfo')),
                ('sendId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendId', to='user_info.userinfo')),
            ],
            options={
                'db_table': 'file_message',
            },
        ),
    ]
