# Generated by Django 3.2 on 2023-08-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0008_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file_vers',
            name='fileId',
            field=models.IntegerField(),
        ),
    ]
