# Generated by Django 3.2 on 2023-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0009_auto_20230830_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_vers',
            name='folderId',
            field=models.IntegerField(default=0),
        ),
    ]
