# Generated by Django 3.2 on 2023-08-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0010_file_vers_folderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_vers',
            old_name='folderId',
            new_name='folderIs',
        ),
    ]
