# Generated by Django 4.2.4 on 2023-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=128, unique=True)),
                ('playerAge', models.CharField(max_length=128)),
                ('playerHeight', models.IntegerField()),
                ('playerWeight', models.IntegerField()),
                ('playerPosition', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
