# Generated by Django 3.2 on 2023-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=128, unique=True)),
                ('userPassword', models.CharField(max_length=128)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userRealName', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
