# Generated by Django 4.2.4 on 2023-08-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=128, unique=True)),
                ('userPassword', models.CharField(max_length=128)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
