# Generated by Django 3.2 on 2023-08-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
        ('group_manage', '0004_auto_20230825_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileId', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=32)),
                ('fileInclude', models.TextField(default='')),
                ('fileUrl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('workId', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('workName', models.CharField(max_length=32)),
                ('isDelete', models.BooleanField(default=False)),
                ('groupIs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manage.group')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageId', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('pageName', models.CharField(max_length=32)),
                ('workIs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_manage.works')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='File_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_manage.files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.userinfo')),
            ],
            options={
                'db_table': 'file_users',
            },
        ),
    ]
