# Generated by Django 3.2 on 2023-08-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Users',
        ),
    ]
