# Generated by Django 3.2 on 2023-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pageId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='works',
            name='workId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
