# Generated by Django 3.2 on 2023-08-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0002_auto_20230824_1722'),
        ('station_manage', '0008_alter_works_create_time'),
    ]

    operations = [
    ]
