# Generated by Django 3.2 on 2023-08-30 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0009_merge_20230830_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('folderId', models.AutoField(primary_key=True, serialize=False)),
                ('folderName', models.CharField(max_length=255)),
                ('file_is_work', models.IntegerField(default='9')),
            ],
            options={
                'db_table': 'folders',
            },
        ),
        migrations.AddField(
            model_name='files',
            name='folderIs',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='files',
            name='fileId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='works',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 14, 24, 55, 358702)),
        ),
    ]
