# Generated by Django 3.2 on 2023-09-02 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_manage', '0010_auto_20230830_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 14, 36, 27, 654349)),
        ),
    ]
